version: "3.9"

services:
  yggdrasil:
    build: ./hypermedia_environment
    container_name: yggdrasil
    environment:
      VERTX_CONFIG_PATH: "conf/config.json"
    ports:
      - "8080:8080" # Expose yggdrasil service on localhost:8080
    networks:
      - app_network

  websub_proxy:
    build:
      context: ./websub_proxy
    container_name: websub_proxy
    environment:
      - FIBER_ENV=production
    command: [ "./main" ]
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
